# Generated by Django 5.2.4 on 2025-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Ожидает'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='todo', max_length=50),
        ),
    ]
