# Generated by Django 5.2.4 on 2025-07-28 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.CharField(max_length=250)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('target_goal', models.IntegerField(null=True)),
                ('unit_of_measure', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(auto_now_add=True, db_index=True)),
                ('goal_status', models.IntegerField(null=True)),
                ('habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_dailyrecords', to='habit_tracker.habit')),
            ],
        ),
    ]
